### ISSUE TITLE
Xdebug 3.1.4 not working with PHP 7.4.28

### ISSUE THREAD

**Issue by cmate5614530** [xdebug/xdebug.org#114]
OS: win 10
Before I used Xdebug v2 with PHP 7.3 and it worked well.
Nowadays I work on a project(it needs php 7.4+) and so I installed another xampp version and configured everything in the same way as before. (using dll wizard)

![image](https://user-images.githubusercontent.com/72118345/162068256-b9ed4d14-2ec6-4dd6-8249-242f7bd3a64d.png)

![image](https://user-images.githubusercontent.com/72118345/162068402-b9640a90-8fbc-4d6c-be80-0610a898e0f4.png)

![image](https://user-images.githubusercontent.com/72118345/162068468-ce7fdd5e-29fe-4f4e-81d6-5aa4313306aa.png)

![image](https://user-images.githubusercontent.com/72118345/162068637-94424d5a-e00f-488c-8f8d-fcc33f4bea10.png)

![image](https://user-images.githubusercontent.com/72118345/162068903-a18ce2d9-4c4d-45e2-924a-7869db63f1b0.png)

Thanks in advance.

**Comment by derickr** [comment]
This is not a support forum, please refer to https://xdebug.org/support — and also read the [upgrade guide](https://xdebug.org/docs/upgrade_guide).
