### ISSUE TITLE
Remove Xcode from the installation instructions

### ISSUE THREAD

**Issue by moritz-t-w** [xdebug/xdebug.org#116]
I use MacOS and **have not installed Xcode from the App Store**, just the command line tools. Yet **XDebug works just fine**. I can't imagine how Xcode would actually be required for it to work... If it isn't, please correct the [instructions](https://xdebug.org/docs/install#pecl) which state the Mac prerequisites as
> Xcode (from the App Store), *and* Xcode's command line tools

The full version of **Xcode takes a huge amount of disk space**. According to [macpaw](https://macpaw.com/how-to/why-xcode-so-big):
> On the App Store page for Xcode, it lists the size of Xcode 12.5 as 11.7GB. However, when you try and install it, you'll get an error message unless you have at least 40GB of free space

**Comment by derickr** [comment]
When you say "Xdebug works just fine", do you mean to say that you compiled Xdebug with just the CLI tools?

**Comment by moritz-t-w** [comment]
I assume so, I followed the rest of the instructions and Xdebug is now installed and working and it wasn't installed before
