### ISSUE TITLE
contributing.php

### ISSUE THREAD

**Issue by 7snovic** [xdebug/xdebug.org#37]
Greeting , I was browsing the website, specially contributing web page, and figured out that in the third section of the web page : 

> Working on a new feature

the issue is with the naming as I guess,
```
Create a feature branch:
git checkout -b issue{issue number}
```
the question is : does that on purpose??

or it's just a typo and you need to update it to : 
```
Create a feature branch:
git checkout -b feature{feature number}
```

and so on.

Regards.

**Comment by derickr** [comment]
I use "issue" for both bugs and features, so the wording is perfectly all right. In the end, it needs an "issue" in the issue tracker at https://bugs.php.net whether it's a bug, or feature.

**Comment by 7snovic** [comment]
Ok, I see.

thanks
