### ISSUE TITLE
Windows compiler MSVC15 doesn't get recognized and marked as VC9?

### ISSUE THREAD

**Issue by jens1o** [xdebug/xdebug.org#39]
Steps to reproduce:

Install PHP 7.2 beta with MSVC15 for Win, you will lose the functionality of most of the extensions.

Open the website:

Provide your `phpinfo()` output

See this line:
![image](https://user-images.githubusercontent.com/11234139/28430352-7f574f1c-6d80-11e7-8b56-14b57d47ae3d.png)

Get this:
![image](https://user-images.githubusercontent.com/11234139/28430356-8a571104-6d80-11e7-9b7b-374fdbcdd00e.png)

**Comment by derickr** [comment]
I think this is solved now.

**Comment by jens1o** [comment]
thanks!
