### ISSUE TITLE
PHP version support?

### ISSUE THREAD

**Issue by daimmo** [xdebug/xdebug.org#44]
When pasting on this page
https://xdebug.org/wizard.php
a phpinfo() of PHP version 5.5.38

I get the following:"PHP versions below 5.5 are not supported."

The issue originates from
https://github.com/xdebug/xdebug.org/blob/master/html/include/phpinfo-scanner.php
on line 253 & 255

**Comment by derickr** [comment]
Fixed through: https://github.com/xdebug/xdebug.org/commit/63456ca5e666b8e21215a7a4d38f593c9d27b5f1
