### ISSUE TITLE
I'm trying to translate the documentation to Chinese.

### ISSUE THREAD

**Issue by 1444910449** [xdebug/xdebug.org#52]
There are many Chinese developers who can only read Chinese. So I'm trying to translate the documentation to Chinese and maintaining a mirror site with Chinese version documentation. Did that abuse any terms or copyright. Is it allowed? 
Thanks for any comments.

**Comment by derickr** [comment]
Hi - I've just answered your email about this I think. Let's keep the discussion there. I'll close this report for now.
