### ISSUE TITLE
Xdebug download page .... awww snap!

### ISSUE THREAD

**Issue by christoferd** [xdebug/xdebug.org#58]
When I load the downloads page
https://xdebug.org/download.php

it sits there loading until Google Chome says "Awww Snap!"

This even occurs with the archived snapshot of the page :-(
https://web.archive.org/web/20190309133508/https://xdebug.org/download.php

**Comment by cookieguru** [comment]
Both links work for me; do you have any extensions that may be causing the problem?  I don't think it's a problem with the site's code; `Awww Snap!` doesn't exist anywhere in the codebase and likely indicates a [Chrome crash](https://support.google.com/chrome/answer/95669)

**Comment by derickr** [comment]
Yeah, this sounds like Chrome just died. Not much I can do about that.
