### ISSUE TITLE
Wizard does not cope with VS19

### ISSUE THREAD

**Issue by rbairwell** [xdebug/xdebug.org#64]
The latest Windows builds of PHP 7.4 ( specifically PHP 7.4 (7.4.0beta2) ) are built using VisualStudio VS16 (`PHP Extension Build => API20190529,NTS,VS16`) which is not accepted by the wizard.

I can see where to fix this in `phpinfo-scanner.php`, but I've got no ways of testing it.

**Comment by derickr** [comment]
PHP.net has dropped VS16 for the PHP 7.4 builds again, so this should no longer be an issue. Thanks for the report though!
