### ISSUE TITLE
[documentation] Debian 10/Buster php-dev install

### ISSUE THREAD

**Issue by peterdd** [xdebug/xdebug.org#69]
On http://xdebug.org/docs/install#compile

> (Debian users can install the required tools with apt-get install php5-dev)

is not true for Debian 10 (Buster) anymore. They just use prefix **php** for php7.3

```
vagrant@debian10:~$ apt search php-dev
Sorting... Done
Full Text Search... Done
php-dev/stable 2:7.3+69 all
  Files for PHP module development (default)
```

**Comment by peterdd** [comment]
On http://xdebug.org/docs/install#debugclient 

> Debian 'unstable' users can install the library with apt-get install libedit-dev libedit2. 

It looks like this is included with Debian 10 (Buster):

```
vagrant@debian10:~$ apt search libedit
Sorting... Done
Full Text Search... Done
libedit-dev/stable 3.1-20181209-1 amd64
  BSD editline and history libraries (development files)

libedit2/stable,now 3.1-20181209-1 amd64 [installed,automatic]
  BSD editline and history libraries
...
```

**Comment by peterdd** [comment]
On http://xdebug.org/docs/faq

> Q: I don't have the phpize tool.
    A: Debian and Ubuntu users need to install the PHP development package with apt install php5-dev, or apt install php7.0-dev for PHP 7.

For Debian 10 it is now just

`apt install php-dev`

For openSUSE Leap 15.1 it is

`zypper install php7-devel`

**Comment by derickr** [comment]
Thanks! I've updated the FAQ. I had already updated your first comment, and I have recently removed the debugclient installation section as it's not really something that people should be using. I suspect ;-) that a new variant will soon exist.
