### ISSUE TITLE
RSS feed broken

### ISSUE THREAD

**Issue by bgoetschke** [xdebug/xdebug.org#74]
Currently the RSS feed does not contain any items.

Seems like commit 5df9729 broke it because the path to the news items in rss.php did not get updated.

**Comment by derickr** [comment]
Could you make a PR? I wont be near a computer to fix this for a while

**Comment by bgoetschke** [comment]
Currently looking into it and noticed there is a require to a fixed path ("_require '/home/derick/dev/zetacomponents/trunk/Base/src/ezc_bootstrap.php';_") in the rss.php instead of using the autoloader. Is there a specific reason to not include "_zetacomponents/feed_" as a composer dependency?

**Comment by bgoetschke** [comment]
This pull request also contains the composer dependency to "_zetacomponents/feed_", in case this is not wanted i can create a new pull request with only the path to the news files changed.

**Comment by derickr** [comment]
Thanks btw! It's now up again.

**Comment by bgoetschke** [comment]
You're welcome! I have to thank you for the years of great work on Xdebug, keep it up! :)
