### ISSUE TITLE
2.8.0 slows down test with code coverage few times

### ISSUE THREAD

**Issue by nightio** [xdebug/xdebug.org#76]
When I started to use v2.8.0 my test with code coverage (1282 tests) takes approx 1,5h compered to ~11min on v2.7.2.

env:
Docker php:7.3.11-fpm-alpine
Framework: Symofny 4.3 with simple-phpunit

**Comment by derickr** [comment]
Hi! You've found the bug tracker for the website of Xdebug. The bug tracker for the extension is not on GitHub. There is already an issue the same as yours filed at https://bugs.xdebug.org/view.php?id=1717
