### ISSUE TITLE
git clone on Windows systems

### ISSUE THREAD

**Issue by 8ctopus** [xdebug/xdebug.org#83]
Hi Derick,
you may want to remove the asterix from the following file so that it checks out properly on Windows systems:

html/docs/include/settings/dump.*.html

When you git clone under windows, you get the following error:

error: unable to create file html/docs/include/settings/dump.*.html: Invalid argument

**Comment by derickr** [comment]
TBH, that sounds like a bug in GIT on Windows, but I'll have a look.

**Comment by derickr** [comment]
Fixed, thanks for the report!

**Comment by 8ctopus** [comment]
yes it's fixed. well done.
