### ISSUE TITLE
remote step debugging

### ISSUE THREAD

**Issue by 8ctopus** [xdebug/xdebug.org#87]
Hi Dereck,

I would like to suggest to create a step by step tutorial on how to get remote step debugging working for first time users. I hit the wall for many hours on how to get it working today and more times in the past. If you're open to such a contribution, I'll happily provide it.

**Comment by derickr** [comment]
Sorry, I've just only seen this.

I'm willing to add these tutorials, as long as they're generic enough. It is also likely that I am going to have strong opinions about it :-) 

What sort of set up are you using?
