### ISSUE TITLE
macOS Catalina build error

### ISSUE THREAD

**Issue by bluemap** [xdebug/xdebug.org#95]
error: unknown warning option '-Wdiscarded-qualifiers'; did you mean '-Wignored-qualifiers'? [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wlogical-op'; did you mean '-Wlong-long'? [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wmaybe-uninitialized'; did you mean '-Wuninitialized'? [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Werror,-Wunknown-warning-option]
make: *** [xdebug.lo] Error 1

**Comment by derickr** [comment]
This is the repository for the Xdebug website, not for the code. That is at https://bugs.xdebug.org — but you're going to have to provide a fair amount of more information for me to do anything with that.
