### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by adriancuadrado** [xdebug/xdebug.org#98]
In [this page](https://xdebug.org/docs/step_debug) you can find between parenthesis this text at the end of the first paragraph of the "Configuring Step Debugging":

> Skip to [Activating the Debugger](https://xdebug.org/docs/activate_debugger) if that's the case.

The "Activating the Debugger" is a broken link.

**Comment by derickr** [comment]
Thanks, the link was missing the `#` anchor.
