### ISSUE TITLE
Ability to click on section titles and get the url with the anchor value

### ISSUE THREAD

**Issue by marciodojr** [xdebug/xdebug.org#99]
Hi,

First of all, thank you for writing the documentation and the Xdebug.

I was reading the Xdebug documentation and I noted that it is not possible (at least with Google Chrome)  to click on a section title and get the url with a suffix to that section. This is a good feature when we want to share a link to a specific topic.

Currently the website already uses anchors in some places but it is not allowed to select it unless you are poking around with "inspect element".

After reading the source code I noted that every section (not sure if is really all of them) has the following format

Page: https://xdebug.org/docs/upgrade_guide section Step Debugging

```html
<a name="Step-Debugging"></a>
<h2>Step Debugging</h2>
```

![image](https://user-images.githubusercontent.com/4480634/103175050-ea8d3c80-4845-11eb-9058-76105ae22ace.png)

If we change the format to

```html
<a name="Step-Debugging" href="#Step-Debugging"><h2>Step Debugging</h2></a>
```
The styles of the tag `a` wll be applied to the `h2` element but we will be able to click and get the url to that section: https://xdebug.org/docs/upgrade_guide#Step-Debugging

![image](https://user-images.githubusercontent.com/4480634/103175032-c598c980-4845-11eb-8707-69c01a787e10.png)

To remove the styles we can apply the following css

```css
.section-anchor {
	color: black;
}
.section-anchor:hover {
	text-decoration: none;
}
.section-anchor:focus {
	outline: none;
}
```
and then add the css class `.section-anchor`

```html
<a name="Step-Debugging" href="#Step-Debugging" class="section-anchor"><h2>Step Debugging</h2></a>
```

Currently there are 216 occurrences of the expression `<a name=*`.

**Comment by derickr** [comment]
In https://xdebug.org/docs/all_settings I have used `#` for that anchor link. I think that's the approach I would want to take in other parts too. I've just committed that patch.
